name: saudeMentalSus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Provider library
  provider: ^4.0.0
  
  # Streaming package
  rxdart: ^0.23.0
  
  # Service locator
  get_it: ^2.0.1
  
  # Bloc for state management
  flutter_bloc: ^3.0.0
  
  # Value equality
  equatable: ^1.0.0
  
  # Functional programming thingies
  dartz: ^0.8.6
  
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  
  # Local cache
  shared_preferences: ^0.5.6

  #Maps dependencies
  google_maps_flutter: ^0.5.21
  geolocator: ^5.1.5
  # Launch Maps
  map_launcher: ^0.7.1
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1

  url_launcher: ^5.5.0
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
